name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest requests pytest-reportlog
          #pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests.py -v --report-log=log/resultlog.jsonl

      - name: Send Results
        run: |
          python sendResults.py --resultlog log/resultlog.jsonl
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
