name: Run Tests and Send Results

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest requests
          #pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      # - name: Send Results to Webhook
      #   run: |
      #     python tests.py
      #   env:
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
